### DISCUSSION TITLE
How to disable autofixes in file name via config?

### DISCUSSION THREAD

**Discussion by jamesbraza** [crate-ci/typos#1269] [Q&A]
I have a `pyproject.toml` for `typos` that resembles this:

```toml
[tool.typos.default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:( )?disable-line$"]

[tool.typos.default.extend-words]
arange = "arange"  # numpy

[tool.typos.files]
extend-exclude = [
    "tests/cassettes/**",
]
```

How can I disable `typos` autofixing typos in file names?

**Comment by jamesbraza** [comment]
I was using `pre-commit` so the solution is to override the `args` to not pass `--write-changes`:

```yaml
  - repo: https://github.com/crate-ci/typos
    rev: v1.30.3
    hooks:
      - id: typos
        args: [--force-exclude]
```

**Comment by epage** [comment]
So this does more than stop autofixes but you can disable spell checking of file names
```toml
[tool.typos.default]
check-filename = false
```
