### DISCUSSION TITLE
`typos` marking typos for words not in `words.csv`

### DISCUSSION THREAD

**Discussion by jamesbraza** [crate-ci/typos#1303] [Q&A] [answered]
I am using `typos` to monitor the emergence of typos across an LLM training.

I have noticed words such as `reductamol` are typos, but `typos` doesn't flag them as such because there's not an entry in `words.csv`.

Is there some CLI flag to configure `typos` to mark any word not matched as a typo?

---

Here is my current `typos` configuration:

```toml
[tool.typos.default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:( )?disable-line$"]

[tool.typos.default.extend-words]
arange = "arange"  # numpy
yhat = "yhat"  # \hat{y}
```
