### DISCUSSION TITLE
How can I extend word list without creating `_typos.toml`

### DISCUSSION THREAD

**Discussion by totoroot** [crate-ci/typos#907] [Q&A] [answered]
I'm using typos mostly as a pre-commit hook for Markdown documentation through [pre-commit-hooks.nix](https://github.com/cachix/pre-commit-hooks.nix).

I have worked on the `typos` hook in the aforementioned repository and would like to extend it.

According to this [section in typos' README](https://github.com/crate-ci/typos#false-positives), to get rid of false-positives, I have to create a `_typos.toml` file and list all spellings I wish to ignore in `[default.extend-words]`.

In many projects it is not desired to have an additional configuration file, especially one that is only for configuring tooling like a pre-commit hook and isn't hidden, like for example `.gitignore`.

Is there a way to extend the word list through a command line argument or any other way that does not require creating this file?

Is this something I should open an issue for?

**Comment by epage** [comment, marked as answer]
Lack of CLI configurability is an intentional design choice to ensure people get consistent runs on the same repo, ie its project configuration.

In a way, you are shifting the project configuration to another location and that is aligned with our goals but I'm still hesitant to open the door on this.  A workaround would be to have your hook write the settings to a temp dir and to use `--isolated --config <path>`.

**Reply by totoroot** [reply]
Thanks for the prompt response! I understand the design decisions and have managed to work around it following your suggestion.

In case anyone is interested how I proposed to facilitate ignoring words for the `typos` hook in [pre-commit-hooks.nix](https://github.com/cachix/pre-commit-hooks.nix), take a look at [this PR](https://github.com/cachix/pre-commit-hooks.nix/pull/392).

**Comment by janosh** [comment]
for other's having the same issue as @totoroot, i tried to follow @epage's advice and arrived at this solution for extending the dictionary directly in `.pre-commit-config.yaml`:

```yml
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos
        name: typos (dynamic config)
        types: [text]
        entry: bash -c 'mkdir -p tmp && printf "[default.extend-words]\\nyau = \"yau\"\\n" > tmp/_typos.toml && exec typos "$@"' --
        args: ['--isolated', '--config', 'tmp/_typos.toml']

```

while it works, it sure would be a lot nicer if there was a `--extend-words` CLI arg so we could do

```yml
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos
        types: [text]
        args: [--extend-words, 'yau,foo']
```
