### ISSUE TITLE
Allow `extend_words` to specify multiple corrections

### ISSUE THREAD

**Issue by tobiasdiez** [crate-ci/typos#1041]
From reading the source code, I get the impressions that typos can already handle multiple corrections for a wrong word. However, when I try to specify the following config
```toml
[default.extend-words]
wrong = ["a", "b"]
```

I get
```
TOML parse error at line 1, column 2
  |
1 | [default.extend-words]
  |  ^^^^^^^
invalid type: sequence, expected a string
```

What's the correct way to specify multiple corrections?

**Comment by szepeviktor** [comment]
Currently you could only say
```toml
[default.extend-words]
wrong = ""
```
error: `wrong` is disallowed
  --> a:1:1
  |
1 | wrong
  | ^^^^^
  |
```

**Comment by epage** [comment]
I'm open to the idea.  The one thing we'd need to figure out is what happens if thr user does
```toml
[default.extend-words]
wrong = ["a", "b", "wrong"]
```
Note that
```toml
[default.extend-words]
right = "right"
```
means "this is always valid"

*When* we get to the implementation, I recommend [serde_untagged](https://crates.io/crates/serde-untagged) over using `#[serde(untagged)]`.
