### ISSUE TITLE
A dictionary with brand name typos

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#1045]
Would it be possible to start a custom dictionary with brand names?

I meet these
```
Github -> GitHub
HashiCorp -> HashiCorp
Wordpress -> WordPress
Big Sur -> Big Sur
```

**Comment by epage** [comment]
Correcting these would be blocked on #795 and #899.

**Comment by szepeviktor** [comment]
Thank you for your response.

So I should keep my default config file with these brand names.
```toml
[default]
extend-ignore-re = [
    "\\bBig Sur\\b",
]

[default.extend-identifiers]
"Github" = "GitHub"
"HashiCorp" = "HashiCorp"
"Wordpress" = "WordPress"
```
