### ISSUE TITLE
Ignore binary files explicitly passed (For use in pre-commit on staged files)

### ISSUE THREAD

**Issue by brandonkal** [crate-ci/typos#1126]
In my [lefthook.yml](https://github.com/evilmartians/lefthook) I have this command that runs before every commit:
```yaml
pre-commit:
  command:
    spelling:
      run: typos --config typos.toml --force-exclude {staged_files}
```
Note that lefthook replaces `{staged_files}` with a spaced list of files that are staged for commit.

It generally works, but if I am committing for example a png or other binary file, it will fail the pre-commit check and I must update my typos.toml like so:
```toml
[files]
extend-exclude = ["*.sops.*", "*.png"]
```
Prettier has `-u,--ignore-unknown`
Eslint has `--no-error-on-unmatched-pattern`

I'm suggesting a cli flag to ignore unsupported files and obvious binary files.

Also the result of `typos --type-list` does not contain `*.svelte` files.
