### ISSUE TITLE
Extend configuration from another file

### ISSUE THREAD

**Issue by jvacek** [crate-ci/typos#1129]
I'd like to have the _entire_ configuration for typos shared among multiple repositories as a base, and be able to override those options locally after inheriting.

It would be nice if there was an option in the config file to extend from another config file, much like `ruff` or `pyright` does.

Currently, for `ruff`, I can for example do something like this in my `pyproject.toml` ([docs](https://docs.astral.sh/ruff/settings/#extend))

```toml
[tool.ruff]
extend = ".company-submodule/ruff.toml"
line-length = 150
```

For `typos`, I would expect it to look something like
```toml
[tool.typos]
extend = ".company-submodule/typos.toml"

[tool.typos.default]
locale = 'en-gb'
```
Where the locale inherited from the submodule's typos.toml would be overwritten by the locally declared `en-gb`

This would imply the following order for sourcing:

> 1. Command line arguments
> 1. File specified via --config PATH
> 1. Search parents of specified file / directory for one of typos.toml, _typos.toml, .typos.toml, Cargo.toml, or pyproject.toml.
>    1. Directly  in the config file
>    2. Inherited from an extended config file
