### ISSUE TITLE
[GitHub Action Integration] Auto comment on PRs with typos or approvals

### ISSUE THREAD

**Issue by datpmt** [crate-ci/typos#1171]
I have just created a [GitHub Actions repository](https://github.com/datpmt/typocop) that uses your `typos` tool to check for typos and automatically comment on PRs or approvals with the following main features:

- Detects typos in files that are part of the pull request.
- Provides a brief output of typos found in each file.
- Comments on the pull request with the results.
- Approve the PR if no typos.
- Dismiss approvals on pull requests if new commit contains typo.
- Delete outdated typos comments.
- Supports all programing languages.

Would it be possible to add a sample action to the "Integration with GitHub" section in your repository?

```yaml
name: Check Typos in Pull Request

on: [pull_request]

jobs:
  typocop:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Typocop Action
        uses: datpmt/typocop@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_id: ${{ github.event.pull_request.number }}
          github_base_ref: ${{ github.base_ref }}
```
