### ISSUE TITLE
GH action not working for windows because of wget

### ISSUE THREAD

**Issue by Its-Just-Nans** [crate-ci/typos#1191]
This actions assumes that `wget` is already installed which is not true for `windows-latest`

This produces the error

```
D:\a\_actions\crate-ci\typos\v1.28.4/action/entrypoint.sh: line 43: wget: command not found
```

The action requires
```yaml
    - name: Install wget for Windows
      if: matrix.os == 'windows-latest'
      run: choco install wget --no-progress
```

Little bit related to #1095
