### ISSUE TITLE
`extend_words` configuration not working when using the GitHub Action

### ISSUE THREAD

**Issue by wopss** [crate-ci/typos#1285]
### Description

The `extend_words` configuration in the GitHub Action is not working. When you add words to `extend_words`, they aren't passed to the `typos` executable. Looking at the [action/entrypoint.sh](https://github.com/crate-ci/typos/blob/6d2159634b251534d46d663fe00a295e06c61515/action/entrypoint.sh), it seems that the `INPUT_EXTEND_WORDS` check is missing, similar to how `INPUT_CONFIG` is handled. The same issue applies to `INPUT_EXTEND_IDENTIFIERS`.

## Example Workflow File

```
name: Spell Check Workflow

on:
  push:
    branches: '**'
  pull_request:

jobs:
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run spell checker
        uses: crate-ci/typos@v1
        with:
          extend_words: typ
```

## Steps to Reproduce

1. Create a GitHub Actions workflow file (e.g., `.github/workflows/spell-check.yml`) with the content provided above.
2. Commit and push the workflow file to the repository.
3. Observe the spell check results in the GitHub Actions run.

## Expected Behavior

The spell checker should recognize and accept the word `typ` as a valid word, as specified in the `extend_words` configuration.

## Actual Behavior

The spell checker does not recognize `typ` as a valid word and flags it as a typo.
