### ISSUE TITLE
Support defining new file types in config

### ISSUE THREAD

**Issue by epage** [crate-ci/typos#220]

**Comment by jaques-sam** [comment]
Thanks for having this, unfortunately for some reason I don't get an error when there's a typo in the "feature" file.

My config `.typos.toml`:
```toml
[type.feature]
extend-glob = ["*.feature"]
check-file = true
```

It does show up in the file types:
```sh
❯ typos --file-types | rg feature
./project/tests/features/new.feature: feature
```

What am I doing wrong?
