### ISSUE TITLE
Typos action v1.0.4 doesn't seem to work as expected

### ISSUE THREAD

**Issue by GuillaumeFalourd** [crate-ci/typos#273]
I tried using the `typos` action using this implementation:

```yaml
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Prepare file with mistakes.
      run: echo "The quick brown foxx jumped over the slepy dog." > file.txt 
    - name: Test with mistakes
      uses: crate-ci/typos@v1.0.4
      with: 
        files: ./file.txt

    - name: Prepare file with no mistakes.
      run: echo "The quick brown fox jumped over the sleepy dog." > file.txt 
    - name: Test with no mistakes
      uses: crate-ci/typos@v1.0.4
      with: 
        files: ./file.txt
 ```
 
 However, both tests are passing without detecting the error in the text with mistakes.
 
**References**
- Github workflow implementation: [full yaml file](https://github.com/GuillaumeFalourd/useful-actions/blob/main/.github/workflows/typos.yml)
- Github workflow execution: [action run](https://github.com/GuillaumeFalourd/useful-actions/runs/2748327968?check_suite_focus=true)

**Did I miss something?**
