### ISSUE TITLE
Exclude one file

### ISSUE THREAD

**Issue by coderaiser** [crate-ci/typos#278]
I want to exclude one file from checking is `ChangeLog`, so I'm tried `.typos.toml`, `typos.tml` and `_typos.toml`:

```toml
[files]
extend-exclude = ["**/ChangeLog"]
```

Or

```toml
[files]
extend-exclude = ["ChangeLog"]
```

Running in a directory with config file:

```sh
typos ChangeLog
```

I see errors:

```
error: `whith` should be `with`
  --> ChangeLog:7:39
  |
7 | - (@putout/plugin-github) description: whith -> with
```

Runninig:

```sh
typos ChangeLog --ignore ChangeLog
```

Gives the same result.

But I need this typos be in `ChangeLog`, that is the log of what I fixed with help of `typos` :).
Thanks a lot for such a nice library.
