### ISSUE TITLE
Missing .pre-commit-hooks.yaml in releases

### ISSUE THREAD

**Issue by xluffy** [crate-ci/typos#283]
I try to add typos to pre-commit config.

```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: double-quote-string-fixer
  - repo: https://github.com/crate-ci/typos
    rev: v1.0.6
    hooks:
      - id: typos
```

But when I create a new commit message, I get an error message:

```
An error has occurred: InvalidManifestError:
=====> /Users/xluffy/.cache/pre-commit/repoev280ri4/.pre-commit-hooks.yaml does not exist
Check the log at /Users/xluffy/.cache/pre-commit/pre-commit.log
```

I try to download latest release at https://github.com/crate-ci/typos/archive/refs/tags/v1.0.6.tar.gz. So when I extract this release, I don't see `.pre-commit-hooks.yaml`. I think this is a issue. Can you help me to release with `.pre-commit-hooks.yaml`?

Thanks
