### ISSUE TITLE
Excluding files unexpected behavior.

### ISSUE THREAD

**Issue by AIGeneratedUsername** [crate-ci/typos#347]
**Current settings:**

__typos.toml_
```toml
[files]
extend-exclude = ["*.json", "**/*.json"]
```

_.pre-commit-config.yaml_
```
-   repo: https://github.com/crate-ci/typos
    rev: typos-v0.7.4
    hooks:
      - id: typos
```

**Expected behavior:**
JSON files must be excluded 

**Expected behavior:**
All files are checked.

**Steps to reproduce**

` pre-commit run typos --all-files`

**Comment by epage** [comment]
`typos` assumes the user knows best when passing in file paths, overriding the exclusions.  Unfortunately, this doesn't layer well with tools like pre-commit.

We need to provide a way to control this behavior.

**Comment by amitlevy21** [comment]
I have the same issue, but only when running `typos-src` with `pre-commit`, running typos from the terminal works fine.
this is my config (_typos.toml at project root directory):
```toml
[files]
extend-exclude = ["src/assets/locales"]

```

locale files are ignored when running from the terminal, but not from `pre-commit run --all-files -v typos-src`

```yaml
  - repo: https://github.com/crate-ci/typos
    rev: v1.3.3
    hooks:
      - id: typos-src
        # args:
        #   - --exclude
        #   - src/assets/locales #uncommenting args works, but its not reading my config file

```

**Comment by kwanhur** [comment]
> `typos` assumes the user knows best when passing in file paths, overriding the exclusions. Unfortunately, this doesn't layer well with tools like pre-commit.
> 
> We need to provide a way to control this behavior.

What about the hook attribute [exclude](https://pre-commit.com/#hooks-exclude) ? It can exclude files with specified pattern.

**Comment by TomaszAIR** [comment]
Hi, we have a little bit different situation

typos.toml

```
$ cat typos.toml 
[files]
extend-exclude = ["Cargo.lock"]
```
.pre-commit-config.yaml

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.4.1
    hooks:
      - id: typos
```

Running couple of times `pre-commit run typos --all-files` gives different results. 2 passes and 1 fail

```
$ pre-commit run --all-files                  
check for added large files..............................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
detect private key.......................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
typos....................................................................Passed
$ pre-commit run --all-files                  
check for added large files..............................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
detect private key.......................................................Passed     
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
typos....................................................................Passed
$ pre-commit run --all-files
check for added large files..............................................Passed
check for merge conflicts................................................Passed                        
check for broken symlinks............................(no files to check)Skipped           
detect private key.......................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
typos....................................................................Failed
```

After that Cargo.lock was changed

```
$ git diff Cargo.lock
diff --git a/Cargo.lock b/Cargo.lock
index 938bfc3b47f7..68cca07e67e5 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -296,7 +296,7 @@ source = "registry+https://github.com/rust-lang/crates.io-index"
 checksum = "d1873270f8f7942c191139cb8a40fd228da6c3fd2fc376d7e92d47aa14aeb59e"
 dependencies = [
  "crypto-common",
- "inout",
+ "input",
 ]
 
 [[package]]
@@ -769,7 +769,7 @@ dependencies = [
 ]
 
 [[package]]
-name = "inout"
+name = "input"
 version = "0.1.2"
```

As if exclusions from `typos.toml` weren't applied every time. Has anyone encountered a similar problem? It looks like a similar case that was here https://github.com/crate-ci/typos/issues/278

**Comment by epage** [comment]
> typos.toml
> 
> ```
> $ cat typos.toml 
> [files]
> extend-exclude = ["Cargo.lock"]
> ```

This is making me realize we should probably centralize all locks into a single file type and have it excluded.

**Comment by epage** [comment]
@TomaszAIR v1.5.0 was just released where we do not check lock files.  This is done in a different way than `extend-exclude` and should work with pre-commit.

**Comment by TomaszAIR** [comment]
@epage thanks for quick fix. Will test that and let you know how it goes.

**Comment by TomaszAIR** [comment]
Yeap, it works. Can confirm that v1.5.0 do not check lock files. None of the `extend-exclude` configuration is needed. Thanks

**Comment by sshishov** [comment]
Hello, when we can expect the fix for the issue? Just a question, not pushing for any actions 😉

**Comment by epage** [comment]
> Hello, when we can expect the fix for the issue?

The core of this is we need a natural mode where we trust the user and a scripted mode where we don't trust the user.  The blocker is defining how to express this in the UI.   Bonus points for including any precedence from other tools

Also want to note that #461 has the workaround of duplicating the exclusions

**Comment by sshishov** [comment]
Thanks @epage , currently as a workaround we started using `pre-commit` exclude, but added `#TODO:` with appropriate comment. And also keep the configuration to exclude in the config file

**Comment by sshishov** [comment]
Additional workaround is:
```
  - repo: https://github.com/crate-ci/typos
    rev: v1.8.1
    hooks:
    - id: typos
      pass_filenames: false
```
Got it from [here](https://github.com/econchick/interrogate/issues/60#issuecomment-735436566) as the same issue exists in [interrogate](https://github.com/econchick/interrogate) package

**Comment by sshishov** [comment]
The same issue as in [isort](https://github.com/PyCQA/isort/issues/938) fixed by [PR 939](https://github.com/PyCQA/isort/pull/939) and [black](https://github.com/psf/black/issues/438) fixed by [PR 1032](https://github.com/psf/black/pull/1032)

Same problem was happening with `flake8` and happening now with [interrogate][(https://github.com/crate-ci/typos/issues/347)](https://github.com/econchick/interrogate/issues/60)

**Comment by epage** [comment]
@sshishov thanks for those examples.  To summarize:
- `isort` added `--filter-files`
- `black` added `--force-exclude`

I wish there was a flag that was common between tools, even if the sample size is just two, as being consistent can be more important than being ideal on its own.

Since these aren't consistent, my next thought is on which more clearly communicates intent.  I feel like isort's only makes sense when reading the docs and thinking about what it is trying to say.  black's makes a little more sense.  "force" make it clear this is a binary flag and that it is overriding some default behavior.  I lean towards that somewhat even though something still feels off to me. Really, we are implicitly forcing the the args to be respected independent of the exclusions.  I just can't think of a succinct way of saying that, so maybe just mirroring black would be best.

If people know of other examples, I'm still open open on this.  At least for me adding the flag, it might be a week or so as I'm trying to wrap up some major work on the clap crate.

**Comment by adamchainz** [comment]
> What about the hook attribute [exclude](https://pre-commit.com/#hooks-exclude) ? It can exclude files with specified pattern.

This is what I'm using. For example:

```yaml
repos:
- repo: https://github.com/crate-ci/typos
  rev: v1.13.10
  hooks:
    - id: typos
      exclude: |
        (?x)^(
          .*\.csv
          |.*\.xml
        )$
```

You can also explicitly limit to certain file types by overriding the `text` type selected in the repo's hook definition:

```yaml
repos:
- repo: https://github.com/crate-ci/typos
  rev: v1.13.10
  hooks:
    - id: typos
      types_or:
      - javascript
      - python
```

IMO one of the powers of pre-commit is that it already passes the correct filenames, based on hook selection and exclusion, so tools don't have to reimplement undifferentiated inclusion/exclusion features.
