### ISSUE TITLE
Error on including ```typos``` Workflow to repository

### ISSUE THREAD

**Issue by Mohitkumar6122** [crate-ci/typos#357]
On adding the ```typos``` workflow to my current repository, on running it is showing failing status like this <br>.

![image](https://user-images.githubusercontent.com/47894634/136738339-7d798b0b-33ba-4fba-b0f3-bd49d9881b42.png)

<br>
Here is the content of my ```typos.yml``` file.

```
name: Test GitHub Action
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master
      with: 
        files: 

    - name: Use custom config file
      uses: crate-ci/typos@master
      with: 
        files: 
        config: ./myconfig.toml

    - name: Ignore implicit configuration file
      uses: crate-ci/typos@master
      with: 
        files: 
        isolated: true
```
Also I want to apply check to the whole repository on adding a new PR, I hope I.m not doing something wrong!?
