### ISSUE TITLE
How to ignore go.sum with pre-commit

### ISSUE THREAD

**Issue by kwanhur** [crate-ci/typos#432]
it doesn't work on this config

```yaml
- repo: git://github.com/crate-ci/typos
  rev: v1.4.0
  hooks:
    - id: typos
      args:
        - --exclude
        - go.sum
```
