### ISSUE TITLE
Ignore SSL cipher suites

### ISSUE THREAD

**Issue by kwanhur** [crate-ci/typos#438]
`typos` ver: 1.4.0 detects cipher suite to correct like:

```bash
error: `EDE` should be `EDGE`
  --> bfe_tls/cipher_suites.go:521:19
    |
521 |  TLS_RSA_WITH_3DES_EDE_CBC_SHA:                 "DES-CBC3-SHA",
    |                    ^^^
    |
```

Hopefully ignore SSL cipher suite format, [openssl ciphers](https://www.openssl.org/docs/man1.1.1/man1/ciphers.html)

**Comment by epage** [comment]
If you weren't aware, typos can be set to ignore these

The following will tell `typos` that `TLS_RSA_WITH_3DES_EDE_CBC_SHA` is a valid identifier and that we shouldn't word-split it and spell check the individual words.
```toml
[default.extend-identifiers]
TLS_RSA_WITH_3DES_EDE_CBC_SHA = "TLS_RSA_WITH_3DES_EDE_CBC_SHA"
```

Would you mind scrounging up what entries should exist?  At minimum, others would be able to reuse it.  I'm also trying to decide if we should bake it directly into `typos` and it'd help get that going.
