### ISSUE TITLE
Explicitly listing input files overrides extend-exclude

### ISSUE THREAD

**Issue by arminrosu** [crate-ci/typos#507]
Hey,

This might not be a bug, but intended, it's just very weird.

Given this configuration file:

```toml
[default.extend-words]
AddOns = "AddOns"

[files]
extend-exclude = [
  '.typos.toml'
]
```

Running `typos --config .typos.toml --format brief .typos.toml` outputs:

```bash
.typos.toml:2:3: `Ons` -> `Owns`
.typos.toml:2:13: `Ons` -> `Owns`
```

That is a bit counter-intuitive, as `.typos.toml` is explictly excluded from typos checking. I noticed this running typos on a `git diff` input.

A way to prevent this is to exclude the files within the `git diff` command, but that makes the config field redundant.

## Versions

- typos: typos-cli 1.10.2
- OS: Mac OS 12.3.1
