### ISSUE TITLE
Unable to correct different capitalizations of the same word

### ISSUE THREAD

**Issue by SeparateRecords** [crate-ci/typos#536]
I'm currently adding this to CI for Fig which is a fairly large Rust + Swift codebase (will have a few typo fixes to contribute 😄)

Currently `iterm` is an unknown word, which is expected and good! We need to let typos know that it's correct for our repo because of iTerm 2.

We have various capitalizations of it: `iterm`, `iTerm`, and `Iterm` - all of which are required in different places due to conventions around identifiers.

Adding this to my `typos.toml` doesn't help:

```toml
[default.extend-identifiers]
iterm = "iterm"
```

<img width="684" alt="CleanShot 2022-08-16 at 21 21 57@2x" src="https://user-images.githubusercontent.com/52195359/184867944-ffb91094-503c-40f7-8349-072bca94b61a.png">

Is this a bug? Am I configuring it wrong?

**Comment by epage** [comment]
You extended the supported identifiers which are case sensitive and do not do word splitting, so it'd need to be
```toml
[default.extend-identifiers]
iterm2 = "iterm2"
Iterm2 = "Iterm2"
```
etc

If you instead
```toml
[default.extend-words]
iterm = "iterm"
```

It should do what you are looking for
