### ISSUE TITLE
Ignore content between certain tags/strings

### ISSUE THREAD

**Issue by davidsneighbour** [crate-ci/typos#544]
Typos will complain about lots of the code samples in README.md here. I wonder if it's possible to either disable it via comments (as plenty of linting tools do) or maybe via a configuration parameter that allows us to ignore things within a certain regular expression. In my specific case I would just want to ignore anything between markdown code samples, like 

``````
``` 
code sample 
```
``````

Is this possible?

**Comment by epage** [comment]
Seeing as typos is targeting spell checking code, could you expand on why you'd want it to ignore code in code fences?

As for ignoring certain lines, we are tracking that in https://github.com/crate-ci/typos/issues/316

**Comment by davidsneighbour** [comment]
I think in documentation of features we often show what NOT to write, an example of this repo's README.md would be this:

```toml
[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# Don't correct the surname "Teh"
teh = "teh"
```

Let's assume I want to write documentation somewhere about this, I would have to add this to my config, so that my documentation is not wrong. On the other side, anywhere else `teh` might be a typo of `the`. Not sure how to describe this properly, but it's probably only a documentation related requirement to show how NOT to write things :) The open issue with the exclusion of lines will probably help to ignore these errors, but those ignore lines would still show up in the highlighted code samples.
