### ISSUE TITLE
Work reported as typo although excluded in `.typos.toml`

### ISSUE THREAD

**Issue by hofbi** [crate-ci/typos#575]
I am using this via pre-commit in version `v1.12.5` and got the following typo reported although I added it to the `extended-words` section in the toml config:

Simple test file:

```
This is a FoV

marking this a corectly wrong
```

The error message:

```
- hook id: typos
- exit code: 2

error: `Fo` should be `Of`, `For`
  --> test:1:11
  |
1 | This is a FoV
  |           ^^
  |
```

The config file:

```toml
[default.extend-words]
# Field of View
FoV = "FoV"

# other test
corectly = "corectly"
```

Do you have any idea, why the ignore does not work for `FoV`. As you can see for `corectly`, the config file work. Could it be related to the camel-case syntax?
