### ISSUE TITLE
Support dashes in `default.extend-identifiers`

### ISSUE THREAD

**Issue by cbachhuber** [crate-ci/typos#646]
Thank you for `typos`, this is an amazing app!

I'd like to be able to have identifiers with dashes in `default.extend-identifiers`. I need it for [gcc's `-Wno-hsa`](https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Warning-Options.html#:~:text=the%20designated_init%20attribute.-,%2DWno%2Dhsa,-Do%20not%20warn) and [clang-tidy's `clang-analyzer-optin`](https://clang.llvm.org/extra/clang-tidy/checks/clang-analyzer/optin.cplusplus.UninitializedObject.html). (Note: [Bare keys with dashes are supported by toml](https://github.com/toml-lang/toml/pull/283))

Does a dash separate two identifiers or is it part of one identifier, similar to an underscore? Should we add this info to the docs? I can't find this anywhere.

Minimal example:

`.typos.toml`:

```toml
[default.extend-identifiers]
wrongWrod = 'wrongWrod'
wrong_wrod = 'wrong_wrod'
wrong-wrod = 'wrong-wrod'  # doesn't have any effect and doesn't warn
```

`example.txt`:

```
wrongWrod
wrong_wrod
wrong-wrod
```

```sh
$ typos example.txt
error: `wrod` should be `word`
  --> file.txt:3:7
  |
3 | wrong-wrod
  |       ^^^^
  |
```
