### ISSUE TITLE
HTTP_REFERER

### ISSUE THREAD

**Issue by brianteeman** [crate-ci/typos#663]
error: `REFERER` should be `REFERRER`
getString('HTTP_REFERER');

Any way to prevent this false positive as HTTP_REFERER is a valid  HTTP header field

**Comment by thedustin** [comment]
I had the same issue in my project, you can add it to your projects typos-configuration:
```toml
# .typos.toml
[default.extend-words]
referer = "referer"
```
(see https://github.com/crate-ci/typos#false-positives)
