### ISSUE TITLE
Simplify contributing to default type-specific dictionaries

### ISSUE THREAD

**Issue by not-my-profile** [crate-ci/typos#759]
The type-specific dictionaries are currently hard-coded in a quite verbose manner, e.g:

https://github.com/crate-ci/typos/blob/84c8b30e065012c70187818aadba0e711ff5cafc/crates/typos-cli/src/config.rs#L210-L226

I think it would be nice to instead have a config file such as:

```toml
[rust.extend_identifiers]
flate2 = "flate2"
[rust.extend_words]
ser = "ser"
```

Just to make contributing such defaults more convenient. The verbose code could still be generated via a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html). An alternative could be a declarative macro, however I think a dedicated .toml file would be nicer because it would enable other projects to easily use the data as well.
