### ISSUE TITLE
GH Action does not work with Alpine

### ISSUE THREAD

**Issue by mvorisek** [crate-ci/typos#769]
repro:
```
name: Unit

on:
  push:

jobs:
  smoke-test:
    name: Smoke
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mvorisek/image-php:${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: ['latest']
        type: ['Phpunit']
        include:
          - php: 'latest'
            type: 'CodingStyle'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Spelling (only for CodingStyle)
        if: matrix.type == 'CodingStyle'
        uses: crate-ci/typos@master
```

CI result: https://github.com/atk4/ui/actions/runs/5378282318/jobs/9757872912#step:10:19
```
 Downloading 'typos' v1.15.5
wget: unrecognized option: progress=dot:mega
BusyBox v1.36.1 (2023-06-02 00:42:02 UTC) multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
	[--post-data STR | --post-file FILE] [-Y on/off]
	[-P DIR] [-U AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	--spider	Only check URL existence: $? is 0 if exists
	--header STR	Add STR (of form 'header: value') to headers
	--post-data STR	Send STR using POST method
	--post-file FILE	Send FILE using POST method
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-o LOGFILE	Log messages to FILE
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy
```

it seems you use non-POSIX `wget` `progress` option.
