### ISSUE TITLE
Ignore a whole word but not an indentifier

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#773]
```
os.O_WRONLY // ignore this
I was doing it WRONLY // but not this
```

I thought
```toml
[default.extend-words]
"os.o_wronly" = "os.o_wronly"
```
would be the solution but I was wrong.

Please help me. Is this a bug?

**Comment by epage** [comment]
`typos` first extracts what it deems to be an identifier.  `os.O_WRONLY // ignore this` gets turned into `[os, O_WRONLY, ignore, this]`.  You can see this with `typos --identifiers`.  You can use `default.extend-identifiers` for controlling the spelling of these.

Next, `typos` then splits identifiers by case and separator (`_`, `-`).  This is what we call "words".

This is somewhat discussed in #744

**Comment by szepeviktor** [comment]
# 🎉 🎉 🎉 

```toml
[default.extend-identifiers]
"O_WRONLY" = "O_WRONLY"
```

This works!
**Must** be uppercase.

**Comment by szepeviktor** [comment]
@epage Could you help ignoring this one too?
```
error: `HAX` should be `HEX`
  --> ./contrib/pcp.py:57:65
   |
57 |     parser.add_argument("-a", action="store_true", help='Pass -aHAX option to rsync.')
   |                                                                 ^^^
   |
```

This is too broad:

```toml
[default.extend-words]
"hax" = "hax"
```

I've tried with several configuration but failed all the time.
Thank you!
