### ISSUE TITLE
Allow providing a reason why a "spelling" is disallowed

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#787]
I run a small list of uninformative words.
https://github.com/szepeviktor/uninformative-words

How it is possible to configure Typos not to fix these words (not identifiers) but output
```
`data` -> `Please add`, `more context`
```
for example in case of `function getData()`

Thank you!

**Comment by szepeviktor** [comment]
So something like
```toml
[default.disallowed-words]
# word = warning message
"data" = "Please add more context"
```
would not work?

**Comment by epage** [comment]
What do you mean it makes `extend-words` stop working?

**Comment by szepeviktor** [comment]
Items under `[default.extend-words]` are not ignored.

**Comment by epage** [comment]
Could you provide a reproduction case
- config
- file content
- description of expected behavior
- description of actual behavior (ideally a copy/paste of command-line and console output)

**Comment by szepeviktor** [comment]
```toml
[default.extend-words]
"data" = []
"echo" = "printf"
```

```php
function getData()
{
    echo 'Typoes';
}
```

Currently `echo` is not corrected to `printf`.
```
error: `Typoes` should be `Typos`, `Types`
  --> ./a.php:3:11
  |
3 |     echo 'Typoes';
  |           ^^^^^^
  |
```

When I remove the line `"data" = []`
```
error: `echo` should be `printf`
  --> ./a.php:3:5
  |
3 |     echo 'Typoes';
  |     ^^^^
  |
error: `Typoes` should be `Typos`, `Types`
  --> ./a.php:3:11
  |
3 |     echo 'Typoes';
  |           ^^^^^^
  |
```

Expected behavior: warn that "data" is being used.
