### ISSUE TITLE
pnpm-lock.yaml is not ignored

### ISSUE THREAD

**Issue by Jiralite** [crate-ci/typos#802]
## Description

There was an effort to stop the spellchecking of lock files with #445. However, I am experiencing this with pnpm-lock.yaml.

## Steps to Reproduce

Using the following .pre-commit-config.yaml:

```YAML
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.4
    hooks:
      - id: typos
        args: []
```

1. `pnpm init`
2. `pnpm add uvu`
3. `typos`

This will be caught:

```
jiralite@Jiralites-MacBook-Pro test % typos
error: `sade` should be `sad`
  --> ./pnpm-lock.yaml:49:7
   |
49 |       sade: 1.8.1
   |       ^^^^
   |
```
