### ISSUE TITLE
Feature request: `default.extend-words-re`

### ISSUE THREAD

**Issue by LilithHafner** [crate-ci/typos#852]
I have a pretty long `typos.toml` file, my project allows abbreviations in variable names, and I don't want to have to keep adding more entries to `typos.toml` whenever a new abbreviation is used. I'd like to exclude all corrections that are 4 or fewer letters long. `default.extend-words-re = ["^[a-zA-Z][a-zA-Z]?[a-zA-Z]?[a-zA-Z]?$"]` seems like a reasonable extension for my repo.

Here's my typos.toml, for reference
```toml
[default.extend-words]
ba = "ba"
egal = "egal"
parm = "parm"
modul = "modul"
fpt = "fpt"
nd = "nd"
strat = "strat"
WRONLY = "WRONLY"
thisy = "thisy"
vally = "vally"
foor = "foor"
Ot = "Ot"
clos = "clos"
applys = "applys"
dne = "dne"
findn = "findn"
mis = "mis"
whos = "whos"
caf = "caf"
seh = "seh"
ue = "ue"
Daa = "Daa"
Missings = "Missings"
SOM = "SOM"
sais = "sais"
LITS = "LITS"
Merly = "Merly"
Filetimes = "Filetimes"
HSA = "HSA"
Strategems = "Strategems"
nce = "nce"
anumber = "anumber"
uupper = "uupper"
shttp = "shttp"
ser = "ser"
somes = "somes"
sav = "sav"
noo = "noo"
egals = "egals"
OLT = "OLT"
eyt = "eyt"
matc = "matc"

# strings in tests directories
fo = "fo"
Uest = "Uest"
Worl = "Worl"
helo = "helo"
bage = "bage"
Dows = "Dows"
truw = "truw"
aquire = "aquire"
noe = "noe"
Hel = "Hel"
nam = "nam"
Facilisi = "Facilisi"
vailable = "vailable"
thre = "thre"
alls = "alls"

# typos that are programmatically observable
compileable = "compileable"
overlayed = "overlayed"

[default.extend-identifiers]
mrs_claus = "mrs_claus"
womens = "womens"
siz = "siz"
breal = "breal"
Breal = "Breal"
Numer = "Numer"
dout = "dout"
splitted = "splitted"
affinitized = "affinitized"
bre = "bre"
key_smove = "key_smove"
readed_zero = "readed_zero"
wee = "wee"
alo = "alo"
laf = "laf"
check_inconsistentcy = "check_inconsistentcy"
blok = "blok"
clen = "clen"
enew = "enew"
ACI = "ACI"
usig = "usig"
eles = "eles"
L_OP_CALLL = "L_OP_CALLL"
OP_CALLL = "OP_CALLL"
nast = "nast"
```
