### ISSUE TITLE
Guidance on extend-exclude for a directory?

### ISSUE THREAD

**Issue by erikspears** [crate-ci/typos#861]
Hi, I've been searching through and reading the Issues (and Readme, of course) around the extend-exclude option with typos, and I'm still hitting a speedbump.  I'd like to implement typos in a GitHub Workflow Action, and after verifying that I've got it finding the config file correctly, I just can't seem to get it to exclude checking a specific directory in our repo.  🤦  Hoping some fresh eyes from someone here can point me to my goof.  🤞 

Workflows Action file:
```
name: Testing spell check

# Only allow manual run of this workflow from the Actions tab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Spell check job
    - name: Check Spelling
      uses: crate-ci/typos@master
      with:
        config: ./.github/workflows/typos.toml
        write_changes: true
```

And here's the `typos.toml` file; it lives in the same directory as the workflow file in the repo (`.github/workflows`):
```
# Exclude the following from spell checking workflow job

[files]
extend-exclude = ["./swirl/tests/"]
```

The directory I'd like to exclude from spell checking is called tests, and it has some subdirectories as well.  I'd like to exlucde all of it.  That dir lives, from the root of the repo, at `./swirl/tests`

I've tried a variety of path syntax in the `extend-exclude` line...a couple examples:

- ["./swirl/tests/*"]
- ["../swirl/tests/"]

Pointer to the public repo, if that helps:  https://github.com/swirlai/swirl-search

Any pointers or guidance much appreciated, thank you!
