### ISSUE TITLE
When is `extend-glob` required in a `[type` section?

### ISSUE THREAD

**Issue by paddyroddy** [crate-ci/typos#871]
I noticed that in the docs there is this example, but is the `extend-glob` required here? I tested a similar case where I omitted and it seemed to work.

```toml
[type.po]
extend-glob = ["*.po"]
check-file = false
```

I'm assuming this is useful if you have a file `x.po1` that you'd like to treat like `x.po`.
