### ISSUE TITLE
Custom dictionaries

### ISSUE THREAD

**Issue by epage** [crate-ci/typos#9]
Source
- passed in on cli
- found on disc

Include
- file type definitions
- per file type corrections

**Comment by epage** [comment]
I realized there are three pieces of information a user may want to specify
- Always valid words
- Always invalid words
- Correctable words

I suspect it might get cumbersome to have 3 custom entries x 2 types of words.

What if the user specifies it as
```toml
[default.dictionary]
invalid=""
valid="valid"
correcton="correction"
```

ie
- Invalid have no correct form
- Valid are their own correct form

We could then implement this as
```rust
enum Correction {
    Invalid,
    Valid,
    Correction(str)
}
```
