### ISSUE TITLE
Don't try to correct `OT` in `OTK`

### ISSUE THREAD

**Issue by dkasak** [crate-ci/typos#900]
`OTK` is a common term in cryptography, standing for One-Time Key. I couldn't quite figure out how to contribute the fix for this, but the following works locally:

```toml
[default.extend-identifiers]
OTK = "OTK"
OTKs = "OTKs"

[default.extend-words]
OTK = "OTK"
OTKs = "OTKs"
```
