### ISSUE TITLE
Typos ignores files in `.gitignore`, even when they are force-tracked in git

### ISSUE THREAD

**Issue by Crown0815** [crate-ci/typos#909]
I have a situation where a typo in a `.png` file's name was corrected in the reference of a `.md` file, but the name of the `.png` file itself was not corrected. 

```
folder
├ my_tipo.png
└ my_docu.md
```

With the content of `my_docu.md`:

```md
[image](./mytipo.png)
```

now `typos` correctly fixes the typo in `my_docu.md` but does not fix the file name of `my_tipo.png` which breaks the link.

Are PNGs not checked in general? Is it possible to have them checked?

I tried adding this to my `_typos.toml` but it did nothing:

```toml
[type.images]
extend-glob = ["*.png"]
check-file = false
```

**Comment by epage** [comment]
If you run `typos --identifiers my_docu.md` you will likely see that `mytipo` is not listed for `my_docu.md`.  Without testing it, my guess is that this is being caught by our URL filter (we can't fix a website...)

As for
```toml
[type.images]
extend-glob = ["*.png"]
check-file = false
```
That is saying to not check the content of `png` files but `check-filename` is likely still true so the file name will be corrected.  This has no affect when a file path ending in `png` is found in a file.
