### ISSUE TITLE
Regex for part of a files contents to include

### ISSUE THREAD

**Issue by uncenter** [crate-ci/typos#945]
I don't see a way to specify a regex for what parts of a file to *include*. It also doesn't help that `look-around, including look-ahead and look-behind, is not supported`. I'd like to be able to do something like this:

```toml
[type.python]
extend-include-re = [
  # Only spellcheck comments
  "#.*"
]
```
