### ISSUE TITLE
false positive with standard Python's Errors

### ISSUE THREAD

**Issue by Borda** [crate-ci/typos#966]
We have just updated via pre-commit auto-update to:
```yaml
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.10
    hooks:
      - id: typos
        args: []  # empty to do not write fixes
```
and since that raising:
```
typos....................................................................Failed
- hook id: typos
- exit code: 2

error: `EOF` should be `OF`
  --> cachier/cores/pickle.py:109:40
    |
109 |             except (FileNotFoundError, EOFError):
    |                                        ^^^
    |
```
